### ISSUE TITLE
test on optuna btb and smac

### ISSUE THREAD

**Issue by WestonLu** [pfnet/optuna#408] opened 2019-05-30 09:24 UTC
## test  description

find the minimum value of (x1-1)**2 + (x2-2)**2 

x1 is a float in [-10 ,10]
x2 is a float in [-10 ,10]

test 100 studies  and  each study has 100 trials

### optuna
```python
import optuna
import time
import numpy as np
optuna.logging.set_verbosity(optuna.logging.ERROR)
start = time.time()
def objective(trial):
    x1 = trial.suggest_uniform('x1', -10, 10)
    x2 = trial.suggest_uniform('x2', -10, 10)
    return  (x1 - 1) ** 2 + (x2 - 2) ** 2

best_score=[]
for i in range(100):
    study = optuna.create_study()
    study.optimize(objective, n_trials=100)
    best_score.append(study.best_value)

end = time.time()
print(np.mean(best_score))
print(end-start)
```

time 
647s 
average of 100 results
0.27

### [btb](https://hdi-project.github.io/BTB/index.html)   

```python
from btb import HyperParameter, ParamTypes
from btb.tuning import GP
import time
import numpy as np
import warnings
warnings.filterwarnings('ignore')

best_score = []

start = time.time()

for i in range(100):
    tunables = [
        ('x1', HyperParameter(ParamTypes.FLOAT, 
                                        [-10, 10])),
        ('x2', HyperParameter(ParamTypes.FLOAT, 
                                        [-10, 10]))
    ]
    tuner = GP(tunables)

    for i in range(100):
        params = tuner.propose()
        #  print('params',params)
        score = -(params['x1'] - 1) ** 2 -  (params['x2'] - 2) ** 2
        tuner.add(params, score)
    best_score.append(tuner._best_score)
    
end = time.time()
print(np.mean(best_score))
print(end-start)
```

time 
264s 
average of 100 results
0.002

**Comment by c-bata** [comment] 2019-05-31 03:54
First, It's better to separate the problem of *speed* and the problem of *optimization's result*.

In general, the time consumed by the optimization library is significantly less than the time taken to evaluate the ML model in the object function. Optuna seems to be slower than btb, but spending about 6 seconds for 100 trials won't be a problem in almost situations. At least, I think keeping a clean design is more important than this problem.

In the viewpoint of performance, Optuna use TPE (The example of btb you pasted uses GP based bayesian optimization). Optuna will support GP based bayesian optimization at #380 and #399.

**Comment by WestonLu** [comment] 2019-05-31 06:19
I am a newcomer to this aspect. Thank you for your patient.  You are right, I realized that the time is indeed not a problem. 
I also made a test on [SMAC](https://github.com/automl/SMAC3), this is just one study. You can see that it's much slower than optuna and btb. 10 trials cost about 55s. But the result is pretty good. 

![image](https://user-images.githubusercontent.com/24969222/58685339-f5ec5d80-83ad-11e9-8c7d-25a0422a7b1d.png)

After all these tests, I found that optuna is much easier for beginners to use. And it also supports saving/resuming studies.  I hope optuna can support more algorithms. Thank you.

**Comment by nmasahiro** [comment] 2019-05-31 07:10
Regarding the difference between the results of Optuna and btb, as mentioned above, I think that it is due to the difference of surrogate models (Optuna uses TPE and btb uses Gaussian Process).
Eggensperger confirmed that Gaussian Process based Bayesian optimization performs better than TPE and SMAC for low-dimensional functions [Eggensperger 13].

And for the results of SMAC, it looks like the initial value of SMAC is given a very good value (the initial value of SMAC is (0, 0) that is near the optimal value (1, 2)).
If you experiment with the different setting, the result may change.

[Eggensperger 13] Eggensperger, K., Feurer, M., Hutter, F., Bergstra, J., Snoek, J., Hoos, H., and Leyton-Brown, K.: Towards an Empirical Foundation for Assessing Bayesian Optimization of Hyperparameters, in NeurIPS workshop on Bayesian Optimization in Theory and Practice (2013).

**Comment by WestonLu** [comment] 2019-05-31 08:40
Thank you. It helps me a lot. Let me paste the result of the [paper](https://ml.informatik.uni-freiburg.de/papers/13-BayesOpt_EmpiricalFoundation.pdf)  here. 

![image](https://user-images.githubusercontent.com/24969222/58692953-4b326a00-83c2-11e9-808e-7b7bdaf99e8d.png)

![image](https://user-images.githubusercontent.com/24969222/58692969-56859580-83c2-11e9-9c4f-4620ccd6ab9d.png)

**Comment by c-bata** [comment] 2019-05-31 09:21
It looks this issue is resolved, right?

**Comment by WestonLu** [comment] 2019-05-31 10:27
@c-bata Yes, please close the issue. Thank you

**Comment by sile** [comment] 2019-05-31 10:30
@c-bata @nmasahiro Thank you for your perfect answers!

I will close this issue.

FYI about execution time
----------------------------

In consideration of safety, Optuna applies `copy.deepcopy()` when trial objects are retrieved from storage.
Besides, `gc.collect()` is called each time a trial is finihsed (https://github.com/pfnet/optuna/pull/377).
In the above test, the overhead of these processing takes most of the execution time (see below):

```console
$ vim optuna-test.py  # Write the above test code

# Execute
$ python optuna-test.py
0.34231789837718446
524.1540217399597    # 524 seconds

# Apply a patch to remove memory copies and GCs
$ patch -p1 <<EOS
> diff --git a/optuna/storages/in_memory.py b/optuna/storages/in_memory.py
> index 7cd63cc..bc5591f 100644
> --- a/optuna/storages/in_memory.py
> +++ b/optuna/storages/in_memory.py
> @@ -253,7 +253,7 @@ class InMemoryStorage(base.BaseStorage):
>
>          self._check_study_id(study_id)
>          with self._lock:
> -            return copy.deepcopy(self.trials)
> +            return self.trials # return copy.deepcopy(self.trials)
>
>      def get_n_trials(self, study_id, state=None):
>          # type: (int, Optional[structs.TrialState]) -> int
> diff --git a/optuna/study.py b/optuna/study.py
> index da99fce..21554ec 100644
> --- a/optuna/study.py
> +++ b/optuna/study.py
> @@ -416,7 +416,7 @@ class Study(object):
>              # environments (e.g., services that use computing containers such as CircleCI).
>              # Please refer to the following PR for further details:
>              # https://github.com/pfnet/optuna/pull/325.
> -            gc.collect()
> +            pass # gc.collect()
>
>          try:
>              result = float(result)
> EOS
patching file optuna/storages/in_memory.py
patching file optuna/study.py

# Re-execute
$ python optuna-test.py
0.3058921208529839
15.914953231811523  # 15 seconds
```

**Closed** 2019-05-31 10:31 UTC
