### ISSUE TITLE
dashboard failed `Lost connection to MySQL server during query`

### ISSUE THREAD

**Issue by Earthson** [pfnet/optuna#275] opened 2018-12-15 11:16 UTC
in the case of idle for a lone time.

**Comment by sile** [comment] 2018-12-17 04:52
Thank you for reporting this problem.

Could you tell us the code (or commands) for reproducing this? And it is very helpful if you could give us the full error messages.

**Comment by Earthson** [comment] 2018-12-17 08:58
```bash
optuna create-study --study test --storage mysql://...

optuna dashboard --study test --storage mysql://...
```

```python
# %%

import optuna

# %%

def objective(trial):
   x = trial.suggest_uniform('x', -10, 10)
   print(type(x), x)
   trial.set_user_attr("accuracy", 0.1)
   trial.set_user_attr("auc", 0.8)
   return (x - 2) ** 2

# %%

study = optuna.Study(study_name='test', storage='mysql://...')

# %%

study.optimize(objective, n_trials=100)
```

**Comment by Earthson** [comment] 2018-12-17 09:33
```
[E 2018-12-17 17:32:39,894] Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x1a1dc45358>: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: 'SELECT studies.study_id AS studies_study_id, studies.study_name AS studies_study_name, studies.direction AS studies_direction \nFROM studies \nWHERE studies.study_id = %s'] [parameters: (2,)] (Background on this error at: http://sqlalche.me/e/e3q8)
File "connections.py", line 276, in query:
_mysql.connection.query(self, query) Traceback (most recent call last):
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/bokeh/application/handlers/code_runner.py", line 163, in run
    exec(self._code, module.__dict__)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/optuna/dashboard.py", line 313, in <module>
    _run()
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/optuna/dashboard.py", line 308, in _run
    app(doc)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/optuna/dashboard.py", line 185, in __call__
    self.study.trials  # type: Optional[List[optuna.structs.FrozenTrial]]
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/optuna/study.py", line 161, in trials
    return self.storage.get_all_trials(self.study_id)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/optuna/storages/rdb/storage.py", line 400, in get_all_trials
    study = models.StudyModel.find_or_raise_by_id(study_id, session)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/optuna/storages/rdb/models.py", line 50, in find_or_raise_by_id
    study = cls.find_by_id(study_id, session)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/optuna/storages/rdb/models.py", line 42, in find_by_id
    study = session.query(cls).filter(cls.study_id == study_id).one_or_none()
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2917, in one_or_none
    ret = list(self)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/Users/earthson/.opt/anaconda/lib/python3.7/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: 'SELECT studies.study_id AS studies_study_id, studies.study_name AS studies_study_name, studies.direction AS studies_direction \nFROM studies \nWHERE studies.study_id = %s'] [parameters: (2,)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by sile** [comment] 2018-12-17 09:43
Thank you for your information. We will investigate the cause.

**Comment by sile** [comment] 2018-12-18 10:32
I investigated it, but I could not reproduce the problem in my environment...
I found a problem such as #278 during the investigation, but it seems to be different from the issue reported by you.
The above error message says "Lost connection to MySQL server during query". So extending the MySQL timeout period may solve the problem, but I'm not sure...

**Comment by g-votte** [comment] 2019-06-24 04:37
Closing the issue. Please reopen if you still have the problem.

**Closed by g-votte** 2019-06-24 04:37 UTC
