### ISSUE TITLE
Discrete_uniform : Range of parameter

### ISSUE THREAD

**Issue by logicwar** [pfnet/optuna#391] opened 2019-05-05 10:17 UTC
While I undertand it is due to the representation of floating point numbers in python and other languages, it would be good if the discrete_uniform range of parameter could be better handled:

Exemple:
     trial.suggest_discrete_uniform('keep_prob', 0.8, 1.0, 0.1)

will produce the following correction: 

     The range of parameter `keep_prob` is not divisible by `q`, and is replaced by [0.8, 0.9].

**Comment by toshihikoyanase** [comment] 2019-05-07 07:51
Thank you for sending your feedback.
We have already recognized the issue, but we plan to keep current implementation for a while. As you mentioned, this is the fundamental issue caused by the representation of floating point numbers, and we think we'll bring a potential risk of future bugs if we handle such values exceptionally.

As a workaround, you can use `trial.suggest_int` instead of `trial.suggest_discrete_uniform`.
For instance, you can rewrite your example code as follows:
```python
# before
trial.suggest_discrete_uniform('keep_prob', 0.8, 1.0, 0.1)
# after
trial.suggest_int('keep_prob', 8, 10) * 0.1
```

**Comment by logicwar** [comment] 2019-05-09 20:05
Understood and thanks for the tip

**Comment by toshihikoyanase** [comment] 2019-05-10 02:12
Thank you for your understanding. Let me close this issue.

If you have further comments, please re-open it.

**Closed by toshihikoyanase** 2019-05-10 02:12 UTC

**Comment by fotisj** [comment] 2019-09-18 23:09
Hi, it may be useful to fix the documentation to reflect this limitation. The example there does not work at the moment: 
    x = trial.suggest_discrete_uniform('x', 0.1, 1.0, 0.1)
[W 2019-09-19 01:03:42,710] The range of parameter `x` is not divisible by `q`, and is replaced by [0.1, 0.9]

**Comment by sile** [comment] 2019-09-19 00:35
@fotisj **FYI** This issue will be resolved by https://github.com/pfnet/optuna/pull/505.
